# Introduction to NumPy

Tamás Gál (tamas.gal@fau.de)

The latest version of this notebook is available at [https://github.com/Asterics2020-Obelics](https://github.com/Asterics2020-Obelics/School2017/tree/master/numpy)

In [1]:
import numpy as np
import sys

print("Python version: {0}\n"
      "NumPy version: {1}"
      .format(sys.version, np.__version__))

Python version: 3.6.0 (default, Jan 30 2017, 16:11:40) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
NumPy version: 1.12.1


In [2]:
def describe(np_obj):
    """Print some information about a NumPy object"""
    print("object type: {0}\n"
          "size: {o.size}\n"
          "shape: {o.shape}\n"
          "ndim: {o.ndim}\n"
          "dtype: {o.dtype}"
          .format(type(np_obj), o=np_obj))

## The basic datastructure in NumPy: `ndarray`

In [3]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [4]:
type(a)

numpy.ndarray

### Array properties

In [5]:
a.size  # number of elements

6

In [6]:
a.shape

(6,)

In [7]:
a.ndim

1

In [8]:
a.dtype

dtype('int64')

### Multi-Dimensional Arrays

In [9]:
b = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [10]:
describe(b)

object type: <class 'numpy.ndarray'>
size: 10
shape: (2, 5)
ndim: 2
dtype: int64


### Array Methods

In [11]:
a.min(), a.max(), a.mean(), a.sum()

(1, 6, 3.5, 21)

In [12]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [13]:
b.sum()

55

In [14]:
b.sum(axis=0)

array([ 7,  9, 11, 13, 15])

In [15]:
b.sum(axis=1)

array([15, 40])

## Operations with Arrays

In [16]:
a

array([1, 2, 3, 4, 5, 6])

In [17]:
a - 23

array([-22, -21, -20, -19, -18, -17])

In [18]:
a * 42 / np.pi

array([ 13.36901522,  26.73803044,  40.10704566,  53.47606088,
        66.8450761 ,  80.21409132])

In [19]:
a**np.e

array([   1.        ,    6.58088599,   19.81299075,   43.30806043,
         79.43235917,  130.38703324])

In [20]:
np.e**a

array([   2.71828183,    7.3890561 ,   20.08553692,   54.59815003,
        148.4131591 ,  403.42879349])

In [21]:
a * a  # element-wise

array([ 1,  4,  9, 16, 25, 36])

In [22]:
       a @ a  # use np.dot(a, a) if you are using Python 2

91

In [23]:
a

array([1, 2, 3, 4, 5, 6])

In [24]:
a < 3

array([ True,  True, False, False, False, False], dtype=bool)

In [25]:
a == 4

array([False, False, False,  True, False, False], dtype=bool)

In [26]:
(a > 3) & (a < 5)

array([False, False, False,  True, False, False], dtype=bool)

In [27]:
a < np.array([2, 3, 5, 2, 1, 5])

array([ True,  True,  True, False, False, False], dtype=bool)

In [28]:
np.sum(a > 2)

4

## Basic Indexing and Slicing

In [29]:
a[0]  # indexing starts at 0

1

In [30]:
a[-1]  # -1 refers to the last element

6

In [31]:
a[2:6:3]  # just like in Python: [start:end:step]

array([3, 6])

In [32]:
a[::-1]  # reversing an array

array([6, 5, 4, 3, 2, 1])

In [33]:
b[::-1]       

array([[ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

### Indixing and Slicing in Multiple Dimensions

In [34]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [35]:
b[0, 2]

3

In [36]:
b[0, 1:4]

array([2, 3, 4])

In [37]:
b[:, 1:4]  # the `:` selects the whole axis

array([[2, 3, 4],
       [7, 8, 9]])

In [38]:
b[:, 2:5:2]

array([[ 3,  5],
       [ 8, 10]])

In [39]:
b[::-1, ::-1]

array([[10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

### Advanced Indexing

In [40]:
d = np.array([4, 3, 2, 5, 4, 5, 4, 4])

In [41]:
mask = np.array([True, False, False, True, False, False, True, True])
mask

array([ True, False, False,  True, False, False,  True,  True], dtype=bool)

In [42]:
d[mask]

array([4, 5, 4, 4])

## The `dtype`

In [43]:
np.dtype

numpy.dtype

In [44]:
a, a.dtype

(array([1, 2, 3, 4, 5, 6]), dtype('int64'))

In [45]:
e = a * 42 / np.pi
e, e.dtype

(array([ 13.36901522,  26.73803044,  40.10704566,  53.47606088,
         66.8450761 ,  80.21409132]), dtype('float64'))

### Some Basic `dtype`s

In [46]:
np.dtype('f')

dtype('float32')

In [47]:
np.dtype('i')

dtype('int32')

In [48]:
np.dtype('i2')

dtype('int16')

In [49]:
np.dtype('i8')

dtype('int64')

In [50]:
np.dtype('f8')

dtype('float64')

In [51]:
np.dtype('S8')  # String with a fixed length of 8

dtype('S8')

### Properties of `dtype`s

In [52]:
dt = np.dtype('>i4')

In [53]:
dt.byteorder

'>'

In [54]:
dt.itemsize

4

In [55]:
dt.name

'int32'

### Structured `dtypes`

In [56]:
dt = np.dtype([('x', 'f8'), ('y', 'f8'), ('E', 'i4')])

In [57]:
dt.itemsize

20

In [58]:
dt['x']

dtype('float64')

## Helper Functions to Create Arrays

In [59]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [60]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [61]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [62]:
np.zeros((2, 4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [63]:
np.empty(20)

array([ -2.31584178e+077,   4.33814323e-311,   4.94065646e-323,
         0.00000000e+000,   2.05833592e-312,   1.16095484e-028,
         7.49232601e+247,   3.97062309e+246,   2.77621464e+184,
         8.76739488e+252,   8.89489936e+252,   5.54175225e+257,
         6.02182527e+151,   9.30537465e+199,   2.20835466e-094,
         5.50028887e+247,   2.15799222e+243,   3.90674185e+233,
         6.99196359e+228,   1.45447205e-308])

In [64]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [65]:
np.linspace(1, 2, 10)

array([ 1.        ,  1.11111111,  1.22222222,  1.33333333,  1.44444444,
        1.55555556,  1.66666667,  1.77777778,  1.88888889,  2.        ])

In [66]:
np.ones_like(b)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Broadcasting

In [67]:
f = np.arange(20)

In [68]:
describe(f)

object type: <class 'numpy.ndarray'>
size: 20
shape: (20,)
ndim: 1
dtype: int64


In [69]:
g = f.reshape(4, 5)

In [70]:
describe(g)

object type: <class 'numpy.ndarray'>
size: 20
shape: (4, 5)
ndim: 2
dtype: int64


In [71]:
g

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [72]:
g.shape

(4, 5)

In [73]:
g * np.arange(5)

array([[ 0,  1,  4,  9, 16],
       [ 0,  6, 14, 24, 36],
       [ 0, 11, 24, 39, 56],
       [ 0, 16, 34, 54, 76]])

to be continued...

## Universal Functions (`ufunc`)

...

## Acknowledgements
![](images/eu_asterics.png)

This tutorial was supported by the H2020-Astronomy ESFRI and Research Infrastructure Cluster (Grant Agreement number: 653477).