# NumPy Exercises

Tamás Gál (tamas.gal@fau.de)

The latest version of this notebook is available at [https://github.com/Asterics2020-Obelics](https://github.com/Asterics2020-Obelics/School2017/tree/master/numpy)

In [1]:
import numpy as np
import sys

print("Python version: {0}\n"
      "NumPy version: {1}"
      .format(sys.version, np.__version__))

Python version: 3.6.0 (default, Jan 30 2017, 16:11:40) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
NumPy version: 1.12.1


In [2]:
def describe(np_obj):
    """Print some information about a NumPy object"""
    print("object type: {0}\n"
          "size: {o.size}\n"
          "ndim: {o.ndim}\n"
          "shape: {o.shape}\n"
          "dtype: {o.dtype}"
          .format(type(np_obj), o=np_obj))

In [3]:
from IPython.core.magic import register_line_magic

@register_line_magic
def shorterr(line):
    """Show only the exception message if one is raised."""
    try:
        output = eval(line)
    except Exception as e:
        print("\x1b[31m\x1b[1m{e.__class__.__name__}: {e}\x1b[0m".format(e=e))
    else:
        return output
    
del shorterr

## Exercise 1: Create a 5x5 matrix with 5's on its diagonal

```5 0 0 0 0
0 5 0 0 0
0 0 5 0 0
0 0 0 5 0
0 0 0 0 5
```

### Solution: `np.eye()`

In [4]:
np.eye(5) * 5

array([[ 5.,  0.,  0.,  0.,  0.],
       [ 0.,  5.,  0.,  0.,  0.],
       [ 0.,  0.,  5.,  0.,  0.],
       [ 0.,  0.,  0.,  5.,  0.],
       [ 0.,  0.,  0.,  0.,  5.]])

### Alternative solutions and further discussions

In [5]:
%timeit np.eye(500) * 5

446 µs ± 91.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
%%timeit
a = np.eye(500)
a  *= 5

496 µs ± 195 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [7]:
%%timeit
a = np.eye(500)
np.multiply(a, 5, out=a)  # avoid creating a copy 

379 µs ± 134 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [8]:
%%timeit
a = np.zeros((500, 500))
# faster on large arrays, no unnecessary multiplications
a[np.diag_indices_from(a)] = 5

135 µs ± 1.25 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [9]:
%timeit np.diag(np.ones(500) * 5)

103 µs ± 1.12 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


## Exercise 2: Create a random array with 10 elements and replace its largest value with 0

### Solution:

In [10]:
a = np.random.random(10)
a

array([ 0.82267982,  0.46855359,  0.50585284,  0.29339295,  0.05869815,
        0.32130992,  0.40092671,  0.35914089,  0.77976176,  0.82588046])

In [11]:
np.argmax(a)  # gives the index of the maximum
a[np.argmax(a)] = 0
a

array([ 0.82267982,  0.46855359,  0.50585284,  0.29339295,  0.05869815,
        0.32130992,  0.40092671,  0.35914089,  0.77976176,  0.        ])

## Exercise 3: Create the following array

    1 2 3 4 5
    1 2 3 4 5
    1 2 3 4 5
    1 2 3 4 5
    1 2 3 4 5


### Solution:

In [12]:
np.ones((5, 5)) * np.arange(1, 6)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 1.,  2.,  3.,  4.,  5.],
       [ 1.,  2.,  3.,  4.,  5.],
       [ 1.,  2.,  3.,  4.,  5.],
       [ 1.,  2.,  3.,  4.,  5.]])

In [13]:
np.ones(5)[:, np.newaxis] * np.arange(1, 6)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 1.,  2.,  3.,  4.,  5.],
       [ 1.,  2.,  3.,  4.,  5.],
       [ 1.,  2.,  3.,  4.,  5.],
       [ 1.,  2.,  3.,  4.,  5.]])

### Alternative solutions and further discussions

In [14]:
%timeit np.ones((500, 5)) * np.arange(1, 6)

18.9 µs ± 4.44 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [15]:
%%timeit
a = np.ones((500, 5))
np.multiply(a, np.arange(1, 6), out=a)

13.3 µs ± 46.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [16]:
%timeit np.ones(500)[:, np.newaxis] * np.arange(1, 6)

18.7 µs ± 212 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [17]:
%%timeit
a = np.empty((500, 5))
a[:] = np.arange(1, 6)

6.27 µs ± 23.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [18]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [19]:
np.ones(5)[:, np.newaxis]  # adds a new dimension

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.]])

In [20]:
np.ones(5)[:, np.newaxis].shape

(5, 1)

In [21]:
np.arange(1, 6).shape

(5,)

In [22]:
# broadcasting will turn (5, 1) and (5,) into (5, 5)
(np.ones(5)[:, np.newaxis] * np.arange(1, 6)).shape

(5, 5)

## Exercise 4: Create a checkerboard (8x8, 0s and 1s)

    0 1 0 1 0 1 0 1
    1 0 1 0 1 0 1 0
    0 1 0 1 0 1 0 1
    1 0 1 0 1 0 1 0
    0 1 0 1 0 1 0 1
    1 0 1 0 1 0 1 0
    0 1 0 1 0 1 0 1
    1 0 1 0 1 0 1 0

### Solution:

In [23]:
checkerboard = np.zeros((8, 8), dtype='i')
checkerboard[::2, 1::2] = 1
checkerboard[1::2, ::2] = 1
checkerboard

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int32)

## Exercise 5: Extract the integer part of a random sample

    np.random.uniform(0, 10, 10)

### Solution:

In [24]:
a = np.random.uniform(0, 10, 10)
a

array([ 0.5779612 ,  5.74321506,  7.34682055,  0.38071745,  0.61419456,
        9.11738166,  8.22188316,  0.40578035,  1.11056097,  7.97025579])

In [25]:
a - a%1

array([ 0.,  5.,  7.,  0.,  0.,  9.,  8.,  0.,  1.,  7.])

In [26]:
np.floor(a)

array([ 0.,  5.,  7.,  0.,  0.,  9.,  8.,  0.,  1.,  7.])

In [27]:
np.ceil(a) - 1

array([ 0.,  5.,  7.,  0.,  0.,  9.,  8.,  0.,  1.,  7.])

In [28]:
np.trunc(a)

array([ 0.,  5.,  7.,  0.,  0.,  9.,  8.,  0.,  1.,  7.])

In [29]:
a.astype(int)

array([0, 5, 7, 0, 0, 9, 8, 0, 1, 7])

### Further discussions

In [30]:
a = np.random.uniform(0, 10, 10000)

In [31]:
%timeit a - a%1

203 µs ± 9.44 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [32]:
%timeit np.floor(a)

55.9 µs ± 1.85 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [33]:
%timeit np.ceil(a) - 1

54.2 µs ± 835 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [34]:
%timeit np.trunc(a)

42.4 µs ± 63.3 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [35]:
%timeit a.astype(int)  # the winner -> casting

6.46 µs ± 54.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## Exercise 6: Create an array with 10 equidistant numbers between 0 and 1, excluding 0 and 1

### Solution:

In [36]:
a = np.linspace(0, 10, 11, endpoint=False)[1:]
a

array([ 0.90909091,  1.81818182,  2.72727273,  3.63636364,  4.54545455,
        5.45454545,  6.36363636,  7.27272727,  8.18181818,  9.09090909])

## Exercise 7: Find the value closest to a given number in an array

    a = np.random.random(10)
    target = 0.23

### Solution:

In [37]:
a = np.random.random(10)
target = 0.23
a

array([ 0.22250948,  0.14942155,  0.11123569,  0.16659427,  0.8230157 ,
        0.62781256,  0.16321913,  0.17916777,  0.36833756,  0.97005432])

In [38]:
a[np.argmin(np.abs(a - target))]

0.22250947730867709

## Acknowledgements
![](images/eu_asterics.png)

This tutorial was supported by the H2020-Astronomy ESFRI and Research Infrastructure Cluster (Grant Agreement number: 653477).