# NumPy Exercises

Tamás Gál (tamas.gal@fau.de)

The latest version of this notebook is available at [https://github.com/Asterics2020-Obelics](https://github.com/Asterics2020-Obelics/School2017/tree/master/numpy)

In [1]:
import numpy as np
import sys

print("Python version: {0}\n"
      "NumPy version: {1}"
      .format(sys.version, np.__version__))

Python version: 3.6.0 (default, Jan 30 2017, 16:11:40) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
NumPy version: 1.12.1


In [2]:
def describe(np_obj):
    """Print some information about a NumPy object"""
    print("object type: {0}\n"
          "size: {o.size}\n"
          "ndim: {o.ndim}\n"
          "shape: {o.shape}\n"
          "dtype: {o.dtype}"
          .format(type(np_obj), o=np_obj))

In [3]:
from IPython.core.magic import register_line_magic

@register_line_magic
def shorterr(line):
    """Show only the exception message if one is raised."""
    try:
        output = eval(line)
    except Exception as e:
        print("\x1b[31m\x1b[1m{e.__class__.__name__}: {e}\x1b[0m".format(e=e))
    else:
        return output
    
del shorterr

## Exercise 1: Create a 5x5 matrix with 5's on its diagonal

```5 0 0 0 0
0 5 0 0 0
0 0 5 0 0
0 0 0 5 0
0 0 0 0 5
```

### Solution: `np.eye()`

In [4]:
np.eye(5) * 5

array([[ 5.,  0.,  0.,  0.,  0.],
       [ 0.,  5.,  0.,  0.,  0.],
       [ 0.,  0.,  5.,  0.,  0.],
       [ 0.,  0.,  0.,  5.,  0.],
       [ 0.,  0.,  0.,  0.,  5.]])

### Alternative solutions and further discussions

In [5]:
%timeit np.eye(500) * 5

400 µs ± 57.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
%%timeit
a = np.eye(500)
np.multiply(a, 5, out=a)  # avoid creating a copy

268 µs ± 6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [7]:
%%timeit
a = np.zeros((500, 500))
a[np.diag_indices_from(a)] = 5  # faster on large arrays, no unnecessary multiplications

148 µs ± 42.3 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


## Exercise 2: Create a random array with 10 elements and replace its largest value with 0

### Solution:

In [8]:
a = np.random.random(10)
a

array([ 0.53098155,  0.22787313,  0.79361196,  0.42715432,  0.59244378,
        0.41181912,  0.81839097,  0.04191163,  0.86892595,  0.64645495])

In [9]:
np.argmax(a)  # gives the index of the maximum
a[np.argmax(a)] = 0
a

array([ 0.53098155,  0.22787313,  0.79361196,  0.42715432,  0.59244378,
        0.41181912,  0.81839097,  0.04191163,  0.        ,  0.64645495])

## Exercise 3: Create the following array

    1 2 3 4 5
    1 2 3 4 5
    1 2 3 4 5
    1 2 3 4 5
    1 2 3 4 5


### Solution:

In [10]:
np.ones((5, 5)) * np.arange(1, 6)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 1.,  2.,  3.,  4.,  5.],
       [ 1.,  2.,  3.,  4.,  5.],
       [ 1.,  2.,  3.,  4.,  5.],
       [ 1.,  2.,  3.,  4.,  5.]])

In [11]:
np.ones(5)[:, np.newaxis] * np.arange(1, 6)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 1.,  2.,  3.,  4.,  5.],
       [ 1.,  2.,  3.,  4.,  5.],
       [ 1.,  2.,  3.,  4.,  5.],
       [ 1.,  2.,  3.,  4.,  5.]])

### Alternative solutions and further discussions

In [12]:
%timeit np.ones((500, 5)) * np.arange(1, 6)

14.8 µs ± 2.28 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [13]:
%%timeit
a = np.ones((500, 5))
np.multiply(a, np.arange(1, 6), out=a)

12.3 µs ± 661 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [14]:
%timeit np.ones(500)[:, np.newaxis] * np.arange(1, 6)

16.6 µs ± 50 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [15]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [16]:
np.ones(5)[:, np.newaxis]

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.]])

In [17]:
np.ones(5)[:, np.newaxis].shape

(5, 1)

In [18]:
np.arange(1, 6).shape

(5,)

In [19]:
(np.ones(5)[:, np.newaxis] * np.arange(1, 6)).shape

(5, 5)

## Acknowledgements
![](images/eu_asterics.png)

This tutorial was supported by the H2020-Astronomy ESFRI and Research Infrastructure Cluster (Grant Agreement number: 653477).