# NumPy Exercises

Tamás Gál (tamas.gal@fau.de)

The latest version of this notebook is available at [https://github.com/Asterics2020-Obelics](https://github.com/Asterics2020-Obelics/School2017/tree/master/numpy)

In [1]:
import numpy as np
import sys

print("Python version: {0}\n"
      "NumPy version: {1}"
      .format(sys.version, np.__version__))

Python version: 3.6.0 (default, Jan 30 2017, 16:11:40) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
NumPy version: 1.12.1


In [2]:
def describe(np_obj):
    """Print some information about a NumPy object"""
    print("object type: {0}\n"
          "size: {o.size}\n"
          "ndim: {o.ndim}\n"
          "shape: {o.shape}\n"
          "dtype: {o.dtype}"
          .format(type(np_obj), o=np_obj))

In [3]:
from IPython.core.magic import register_line_magic

@register_line_magic
def shorterr(line):
    """Show only the exception message if one is raised."""
    try:
        output = eval(line)
    except Exception as e:
        print("\x1b[31m\x1b[1m{e.__class__.__name__}: {e}\x1b[0m".format(e=e))
    else:
        return output
    
del shorterr

## Exercise 1: Create a 5x5 matrix with 5's on its diagonal

```5 0 0 0 0
0 5 0 0 0
0 0 5 0 0
0 0 0 5 0
0 0 0 0 5
```

### Solution: `np.eye()`

In [4]:
np.eye(5) * 5

array([[ 5.,  0.,  0.,  0.,  0.],
       [ 0.,  5.,  0.,  0.,  0.],
       [ 0.,  0.,  5.,  0.,  0.],
       [ 0.,  0.,  0.,  5.,  0.],
       [ 0.,  0.,  0.,  0.,  5.]])

### Alternative solutions and further discussions

In [5]:
%timeit np.eye(500) * 5

362 µs ± 4.62 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
%%timeit
a = np.eye(500)
np.multiply(a, 5, out=a)  # avoid creating a copy

266 µs ± 2.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [7]:
%%timeit
a = np.zeros((500, 500))
# faster on large arrays, no unnecessary multiplications
a[np.diag_indices_from(a)] = 5

121 µs ± 635 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


## Exercise 2: Create a random array with 10 elements and replace its largest value with 0

### Solution:

In [8]:
a = np.random.random(10)
a

array([ 0.17490851,  0.913733  ,  0.41855316,  0.63531874,  0.74296014,
        0.07120757,  0.5803241 ,  0.5835063 ,  0.32090346,  0.73763625])

In [9]:
np.argmax(a)  # gives the index of the maximum
a[np.argmax(a)] = 0
a

array([ 0.17490851,  0.        ,  0.41855316,  0.63531874,  0.74296014,
        0.07120757,  0.5803241 ,  0.5835063 ,  0.32090346,  0.73763625])

## Exercise 3: Create the following array

    1 2 3 4 5
    1 2 3 4 5
    1 2 3 4 5
    1 2 3 4 5
    1 2 3 4 5


### Solution:

In [10]:
np.ones((5, 5)) * np.arange(1, 6)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 1.,  2.,  3.,  4.,  5.],
       [ 1.,  2.,  3.,  4.,  5.],
       [ 1.,  2.,  3.,  4.,  5.],
       [ 1.,  2.,  3.,  4.,  5.]])

In [11]:
np.ones(5)[:, np.newaxis] * np.arange(1, 6)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 1.,  2.,  3.,  4.,  5.],
       [ 1.,  2.,  3.,  4.,  5.],
       [ 1.,  2.,  3.,  4.,  5.],
       [ 1.,  2.,  3.,  4.,  5.]])

### Alternative solutions and further discussions

In [12]:
%timeit np.ones((500, 5)) * np.arange(1, 6)

12.4 µs ± 64.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [13]:
%%timeit
a = np.ones((500, 5))
np.multiply(a, np.arange(1, 6), out=a)

11.7 µs ± 124 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [14]:
%timeit np.ones(500)[:, np.newaxis] * np.arange(1, 6)

16.5 µs ± 102 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [15]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [16]:
np.ones(5)[:, np.newaxis]  # adds a new dimension

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.]])

In [17]:
np.ones(5)[:, np.newaxis].shape

(5, 1)

In [18]:
np.arange(1, 6).shape

(5,)

In [19]:
# broadcasting will turn (5, 1) and (5,) into (5, 5)
(np.ones(5)[:, np.newaxis] * np.arange(1, 6)).shape

(5, 5)

## Exercise 4: Create a checkerboard (8x8, 0s and 1s)

    0 1 0 1 0 1 0 1
    1 0 1 0 1 0 1 0
    0 1 0 1 0 1 0 1
    1 0 1 0 1 0 1 0
    0 1 0 1 0 1 0 1
    1 0 1 0 1 0 1 0
    0 1 0 1 0 1 0 1
    1 0 1 0 1 0 1 0

### Solution:

In [20]:
checkerboard = np.zeros((8, 8), dtype='i')
checkerboard[::2, 1::2] = 1
checkerboard[1::2, ::2] = 1
checkerboard

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int32)

## Exercise 5: Extract the integer part of a random sample

    np.random.uniform(0, 10, 10)

### Solution:

In [21]:
a = np.random.uniform(0, 10, 10)
a

array([ 2.46821636,  8.50032649,  3.73099993,  8.06425165,  1.77990712,
        9.96164056,  0.29684195,  4.15286284,  5.99561503,  0.73784658])

In [22]:
a - a%1

array([ 2.,  8.,  3.,  8.,  1.,  9.,  0.,  4.,  5.,  0.])

In [23]:
np.floor(a)

array([ 2.,  8.,  3.,  8.,  1.,  9.,  0.,  4.,  5.,  0.])

In [24]:
np.ceil(a) - 1

array([ 2.,  8.,  3.,  8.,  1.,  9.,  0.,  4.,  5.,  0.])

In [25]:
np.trunc(a)

array([ 2.,  8.,  3.,  8.,  1.,  9.,  0.,  4.,  5.,  0.])

In [26]:
a.astype(int)

array([2, 8, 3, 8, 1, 9, 0, 4, 5, 0])

### Further discussions

In [27]:
a = np.random.uniform(0, 10, 10000)

In [28]:
%timeit a - a%1

179 µs ± 13.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [29]:
%timeit np.floor(a)

45.6 µs ± 4.85 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [30]:
%timeit np.ceil(a) - 1

47.8 µs ± 1.17 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [31]:
%timeit np.trunc(a)

37.3 µs ± 479 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [32]:
%timeit a.astype(int)  # the winner -> casting

5.72 µs ± 55.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## Exercise 6: Create an array with 10 equidistant numbers between 0 and 1, excluding 0 and 1

### Solution:

In [33]:
a = np.linspace(0, 10, 12)[1:-1]
a

array([ 0.90909091,  1.81818182,  2.72727273,  3.63636364,  4.54545455,
        5.45454545,  6.36363636,  7.27272727,  8.18181818,  9.09090909])

## Exercise 7: Find the value closest to a given number in an array

    a = np.random.random(10)
    target = 0.23

### Solution:

In [34]:
a = np.random.random(10)
target = 0.23
a

array([ 0.32104686,  0.8846238 ,  0.18253567,  0.73023177,  0.53023707,
        0.2328745 ,  0.95506632,  0.35435579,  0.05175267,  0.21213614])

In [35]:
a[np.argmin(np.abs(a - 0.3))]

0.32104685635706542

## Acknowledgements
![](images/eu_asterics.png)

This tutorial was supported by the H2020-Astronomy ESFRI and Research Infrastructure Cluster (Grant Agreement number: 653477).