# Nearest Points Exercise

Tamás Gál (tamas.gal@fau.de)

The latest version of this notebook is available at [https://github.com/Asterics2020-Obelics](https://github.com/Asterics2020-Obelics/School2017/tree/master/numpy)

In [1]:
import numpy as np
import sys

print("Python version: {0}\n"
      "NumPy version: {1}"
      .format(sys.version, np.__version__))

Python version: 3.6.0 (default, Jan 30 2017, 16:11:40) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
NumPy version: 1.12.1


## Given an array of points (in 3D), find the nearest point for each one.

In [2]:
N = 500
n_dims = 3
points = np.random.random((N, n_dims))
points

array([[ 0.48654408,  0.8506339 ,  0.70842765],
       [ 0.798706  ,  0.5837321 ,  0.46619427],
       [ 0.96955324,  0.12721823,  0.42119987],
       ..., 
       [ 0.36307395,  0.79875506,  0.7705336 ],
       [ 0.7227237 ,  0.76614387,  0.01895881],
       [ 0.03738323,  0.25039983,  0.70914375]])

### Solution

In [3]:
N = 4
n_dims = 3
points = np.random.random((N, n_dims))
points

array([[ 0.92260939,  0.95912449,  0.013602  ],
       [ 0.76338567,  0.76389733,  0.85732368],
       [ 0.75174152,  0.59695115,  0.35160294],
       [ 0.39305052,  0.82128872,  0.41424067]])

In [4]:
distances = np.sum((points.reshape(N, 1, n_dims) - points)**2, axis=2)
distances[np.diag_indices_from(distances)] = np.inf
np.argmin(distances, axis=1)

array([2, 2, 3, 2])

### Discussion

In [5]:
points

array([[ 0.92260939,  0.95912449,  0.013602  ],
       [ 0.76338567,  0.76389733,  0.85732368],
       [ 0.75174152,  0.59695115,  0.35160294],
       [ 0.39305052,  0.82128872,  0.41424067]])

In [6]:
points.shape

(4, 3)

In [7]:
reshaped_points = points.reshape(N, 1, n_dims)
reshaped_points

array([[[ 0.92260939,  0.95912449,  0.013602  ]],

       [[ 0.76338567,  0.76389733,  0.85732368]],

       [[ 0.75174152,  0.59695115,  0.35160294]],

       [[ 0.39305052,  0.82128872,  0.41424067]]])

In [8]:
reshaped_points.shape

(4, 1, 3)

In [9]:
differences = reshaped_points - points
differences

array([[[ 0.        ,  0.        ,  0.        ],
        [ 0.15922371,  0.19522716, -0.84372168],
        [ 0.17086786,  0.36217334, -0.33800094],
        [ 0.52955886,  0.13783578, -0.40063867]],

       [[-0.15922371, -0.19522716,  0.84372168],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.01164415,  0.16694618,  0.50572073],
        [ 0.37033515, -0.05739138,  0.44308301]],

       [[-0.17086786, -0.36217334,  0.33800094],
        [-0.01164415, -0.16694618, -0.50572073],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.358691  , -0.22433756, -0.06263772]],

       [[-0.52955886, -0.13783578,  0.40063867],
        [-0.37033515,  0.05739138, -0.44308301],
        [-0.358691  ,  0.22433756,  0.06263772],
        [ 0.        ,  0.        ,  0.        ]]])

In [10]:
print(reshaped_points.shape, " - ", points.shape, " => ", differences.shape)

(4, 1, 3)  -  (4, 3)  =>  (4, 4, 3)


In [11]:
distances = np.sum(differences**2, axis=2)
distances

array([[ 0.        ,  0.7753321 ,  0.27460999,  0.45994263],
       [ 0.7753321 ,  0.        ,  0.28376007,  0.33676445],
       [ 0.27460999,  0.28376007,  0.        ,  0.18291006],
       [ 0.45994263,  0.33676445,  0.18291006,  0.        ]])

In [12]:
distances.shape

(4, 4)

In [13]:
distances

array([[ 0.        ,  0.7753321 ,  0.27460999,  0.45994263],
       [ 0.7753321 ,  0.        ,  0.28376007,  0.33676445],
       [ 0.27460999,  0.28376007,  0.        ,  0.18291006],
       [ 0.45994263,  0.33676445,  0.18291006,  0.        ]])

In [14]:
# get rid of self-distances first ;)
distances[np.diag_indices_from(distances)] = np.inf

In [15]:
distances

array([[        inf,  0.7753321 ,  0.27460999,  0.45994263],
       [ 0.7753321 ,         inf,  0.28376007,  0.33676445],
       [ 0.27460999,  0.28376007,         inf,  0.18291006],
       [ 0.45994263,  0.33676445,  0.18291006,         inf]])

In [16]:
nearest_points = np.argmin(distances, axis=1)
nearest_points

array([2, 2, 3, 2])

### Comparing to `scikit-learn`

In [17]:
nearest_points

array([2, 2, 3, 2])

In [18]:
from sklearn.neighbors import NearestNeighbors
_, indices = NearestNeighbors().fit(points).kneighbors(points, 2)
indices[:, 1]

array([2, 2, 3, 2])

In [19]:
%timeit _, indices = NearestNeighbors().fit(points).kneighbors(points, 2)

131 µs ± 12.6 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [20]:
%%timeit
distances = np.sum((points.reshape(N, 1, n_dims) - points)**2, axis=2)
distances[np.diag_indices_from(distances)] = np.inf
np.argmin(distances, axis=1)

31.8 µs ± 509 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


#### Our implementation is faster just because of the function call overhead of scikit-learn. Try bigger `N`s and see how they actually compare to each other.